name: Node.js Setup

on: workflow_call

env:
  NODE_VERSION: 18

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION

      - name: Install Dependencies
        run: npm ci
